version: "3.2"  
services:
  postgres:
    container_name: lambdaorm-svc-postgres
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_DB=northwind    
      - POSTGRES_USER=northwind
      - POSTGRES_PASSWORD=northwind
    volumes:
      - ./volume/postgres-data:/var/lib/postgresql/data
    ports:
      - '5436:5432'
    expose:
      - 5436  
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "northwind" ]
      interval: 3s
      timeout: 1s
      retries: 10 
  lambdaorm-api:
    depends_on:
      - postgres
    container_name: lambdaorm-svc-api
    image: flaviorita/lambdaorm-svc:0.6.2
    # build:
    #   context: ./../../../../
    restart: always  
    environment:
      - HOST=http://localhost
      - PORT=9292
      - WORKSPACE=/workspace
      - CNN_POSTGRES={"host":"0.0.0.0","port":5436,"user":"northwind","password":"northwind","database":"northwind"}
    # Se configuro network mode host por que cuando se intentaba conectar desde este contenedor al postgress, daba error de conexion
    # TODO: configurar nuevamente como network y resolver el problema.
    network_mode: host  
    volumes:
      - ./workspace:/workspace  
